version: '3.0'
services:
  node:
    build: .
    restart: on-failure
    networks:
      - my-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${NODE_PORT}
  postgres:
    build: ./database/
    restart: on-failure
    networks:
      - my-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSRGRES_USER: ${POSRGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSRGRES_PASSWORD: ${POSRGRES_POSRGRES_PASSWORD}
      POSRGRES_DB: ${POSRGRES_DB}

networks:
  my-network:
    driver: bridge

